import { facts } from '../facts.js';
import { qwen38Spatial } from './spatial-qwen38.js?v=4';
import { kimiK3Spatial } from './spatial-kimi.js?v=7';
import { glm5Spatial } from './spatial-glm5.js?v=4';
import { deepseekV4Spatial } from './spatial-deepseek-v4.js?v=4';
import { gemma4Spatial } from './spatial-gemma4.js?v=3';
import { minimaxM25Spatial } from './spatial-minimax.js?v=3';
import { step35Spatial } from './spatial-step35.js?v=1';

const originalFacts = {
  ...facts.original,
  routedExperts: 0,
  activeExperts: 0,
  sharedExperts: 0,
  residualStreams: 1,
  window: 0,
  topk: 0,
  candidatePool: 0,
  fullLayers: [],
  reindexLayers: [],
  encoder: 6,
  cacheBytes: 0,
  metricResidual: 'Add & Norm<small>one residual stream · post-LayerNorm</small>',
};

const deepseekFacts = { ...facts.deepseek };

export const MODELS = [
  {
    id: 'original',
    name: 'Original Transformer',
    short: 'Transformer',
    year: '2017',
    tagline: '6 encoder + 6 decoder',
    accent: 0xedb565,
    modern: false,
    source: 'glb',
    glb: 'spatial-original',
    glbIndex: 0,
    facts: originalFacts,
    summary: 'Vaswani et al. 2017 English-to-German base: 65M, 6+6 layers, dense attention, tied embeddings.',
    sources: [
      { title: 'Attention Is All You Need', url: 'https://arxiv.org/html/1706.03762v7', note: 'Figure 1, §3 and Table 3. 65M English-to-German base.' },
    ],
    notes: ['Sequence-to-sequence: the decoder consumes a separate, shifted target sequence.'],
    roles: { attn:'encoder_attention', sparse:'decoder_attention', index:null, moe:'encoder_ffn', residual:'encoder_norm1', memory:null, vision:null, projector:null, head:'softmax', draft:'softmax' },
    beats: {
      stack:'6 encoder + 6 decoder · 65M dense seq2seq.',
      attn:'8-head dense self-attention.',
      sparse:'Dense causal masking; no retrieval index.',
      moe:'Dense ReLU FFN, width 2,048.',
      residual:'One residual stream, post-LayerNorm.',
      memory:'No extra parameter memory.',
      vision:'Text tokens only.',
      output:'Tied softmax, one token at a time.',
    },
  },
  {
    id: 'deepseek',
    name: 'DeepSeek V4.1 Flash',
    short: 'DeepSeek V4.1',
    year: '2026',
    tagline: '20 encoder + 20 decoder',
    accent: 0x65d9ce,
    modern: true,
    source: 'glb',
    glb: 'spatial-deepseek',
    glbIndex: 1,
    facts: deepseekFacts,
    summary: 'CSA2 + local SWA, Engram, DSpark. 552B backbone + 196B Engram.',
    sources: [
      { title: 'DeepSeek-V4.1-Flash report', url: 'https://huggingface.co/deepseek-ai/DeepSeek-V4.1-Flash/blob/main/DeepSeek_V41_Tech_Report.pdf', note: 'Figures 3–5; §2, §3.2.2 and §4.2.1.' },
      { title: 'Official config', url: 'https://huggingface.co/deepseek-ai/DeepSeek-V4.1-Flash/blob/main/config.json', note: 'Checked against the saved configuration.' },
    ],
    notes: ['The authored DeepSeek tour is used when V4.1 Flash is paired with the 2017 Transformer.'],
    roles: { attn:'encoder_full', sparse:'decoder_full', index:'candidate_pool', moe:'encoder_moe_full', residual:'embedding', memory:'engram', vision:'vision_encoder', projector:'vision_embedding', head:'target_head', draft:'dspark' },
    beats: {
      stack:'20+20 causal layers · CSA2 + SWA.',
      attn:'64 Q heads, shared latent KV.',
      sparse:'Sparse global retrieval + 128-token local window.',
      moe:'6 of 384 routed experts + 1 shared.',
      residual:'4 streams, Single-Pass mHC.',
      memory:'Engram ×2, 196B lookup parameters.',
      vision:'32-layer vision encoder, 14-px patches.',
      output:'Untied head + optional DSpark drafts.',
    },
  },
  {
    id: 'deepseek-v4',
    name: 'DeepSeek V4',
    short: 'DeepSeek V4',
    year: '2026',
    tagline: '61 layers · 6+1 / 384',
    accent: 0x14b8a6,
    modern: true,
    source: 'build',
    spatial: deepseekV4Spatial,
    facts: {
      layers: 61, encoder: 0, decoder: 61, hidden: 7168, heads: 128, headDim: 512,
      routedExperts: 384, activeExperts: 6, sharedExperts: 1, expertHidden: 3072,
      window: 128, topk: 1024, candidatePool: 16384, cacheBytes: 0, context: 1048576,
      fullLayers: [0, 1], reindexLayers: [], residualStreams: 4,
      metricResidual: '4 streams<small>mHC · hc_mult 4</small>',
      metricDraft: 'MTP<small>1 extra layer · multi-token prediction</small>',
      metricHead: 'Vocabulary head<small>129,280 entries</small>',
      vocab: 129280,
    },
    summary: 'DeepSeek-V4-Pro config: 1.6T / 49B, 61 layers. First 2 HCA, then CSA/HCA; mHC residual; Hash-MoE on the first 3 layers.',
    sources: [
      { title: 'Official config.json', url: 'https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro/blob/main/config.json', note: 'DeepseekV4ForCausalLM: 61 layers, 384 routed experts, index_topk=1024, 1M context.' },
      { title: 'Technical report', url: 'https://arxiv.org/html/2606.19348', note: 'DeepSeek-V4: Towards Highly Efficient Million-Token Context Intelligence.' },
      { title: 'Model card', url: 'https://huggingface.co/deepseek-ai/DeepSeek-V4-Pro', note: '1.6T total, 49B active; hybrid CSA + HCA; MTP retained from V3.' },
    ],
    notes: [
      'This drawing follows the V4-Pro checkpoint, not V4-Flash (43 layers, 256 experts) or V4.1 Flash.',
      'Every HCA layer, including the first two, compresses KV 128× then runs dense MQA; CSA compresses 4× then indexes top-k 1,024. Both add a 128-token uncompressed sliding window.',
      'Hash-MoE replaces dense FFNs on the first 3 layers (2 HCA + the first CSA). The unrolled CSA FFN in the repeating cell is ordinary routed MoE.',
    ],
    roles: { attn:'encoder_hca0', sparse:'encoder_csa', index:'candidate_pool', moe:'encoder_moe_csa', residual:'embedding', memory:'hca_kv', vision:null, projector:null, head:'target_head', draft:'mtp' },
    beats: {
      stack:'61 layers · 1.6T / 49B; first 2 HCA then CSA/HCA.',
      attn:'HCA: 128× compressed KV, dense MQA, plus 128-token SWA.',
      sparse:'CSA: 4× compressed KV, indexer top-k 1,024, plus SWA.',
      moe:'6 of 384 routed experts + 1 shared; Hash-MoE on the first 3 layers.',
      residual:'4-stream mHC residual.',
      memory:'HCA 128× KV is used from the first layer; CSA keeps a separate 4× cache.',
      vision:'Text-only in this drawing.',
      output:'Untied vocabulary head + MTP.',
    },
  },
  {
    id: 'qwen38',
    name: 'Qwen3.8-Flash-Next',
    short: 'Qwen3.8',
    year: '2026',
    tagline: '48 layers · 10+1 / 512',
    accent: 0x4d8dff,
    modern: true,
    source: 'build',
    spatial: qwen38Spatial,
    facts: {
      layers: 48, encoder: 0, decoder: 48, hidden: 2560, heads: 24, headDim: 256,
      routedExperts: 512, activeExperts: 10, sharedExperts: 1, expertHidden: 640,
      window: 2048, topk: 2048, candidatePool: 16384, cacheBytes: 0, context: 262144,
      fullLayers: [3], reindexLayers: [], residualStreams: 4,
      metricResidual: '4 streams<small>Gated Residual · rank 320</small>',
      metricVision: 'Native vision<small>patch features projected into 2,560-d text space</small>',
      metricEngram: '51B n-gram<small>layer 2 · host-offloadable tables</small>',
      metricDraft: 'MTP<small>1 extra layer · multi-token training</small>',
      metricHead: 'Vocabulary head<small>248,320 entries</small>',
      vocab: 248320,
    },
    summary: 'Qwen4 preview: 125B+51B n-gram, 6B active. 12 × (3×GDN + 1×QSA), 4-branch Gated Residual.',
    sources: [
      { title: 'Hugging Face model card', url: 'https://huggingface.co/Qwen/Qwen3.8-Flash-Next', note: '125B backbone, 6B active, 51B n-gram, 4B MTP; 48-layer hybrid layout.' },
      { title: 'Technical report', url: 'https://arxiv.org/html/2608.30320', note: 'On the Design of Qwen3.8-Next Architecture.' },
    ],
    notes: [
      'The drawing unrolls one hybrid cell; the outer cage is ×12, not shared weights.',
      'QSA indexer budget is 512 blocks or 2,048 tokens, not dense full-sequence attention.',
    ],
    roles: { attn:'encoder_gdn0', sparse:'encoder_qsa', index:'candidate_pool', moe:'encoder_moe_qsa', residual:'embedding', memory:'ngram', vision:'vision_encoder', projector:'vision_embedding', head:'target_head', draft:'mtp' },
    beats: {
      stack:'48 hybrid layers · 125B+51B, 6B active.',
      attn:'Gated DeltaNet, 24 Q / 2 KV.',
      sparse:'QSA every 4th layer; indexer budget 2,048 tokens.',
      moe:'10 of 512 routed experts + 1 shared.',
      residual:'4-branch Gated Residual, rank 320.',
      memory:'51B n-gram tables at layer 2.',
      vision:'Native vision encoder into 2,560-d text space.',
      output:'LM head + 1-layer MTP.',
    },
  },
  {
    id: 'kimi-k3',
    name: 'Kimi K3',
    short: 'Kimi K3',
    year: '2026',
    tagline: '93 layers · 16+2 / 896',
    accent: 0xa78bfa,
    modern: true,
    source: 'build',
    spatial: kimiK3Spatial,
    facts: {
      layers: 93, encoder: 0, decoder: 93, hidden: 7168, heads: 96, headDim: 128,
      routedExperts: 896, activeExperts: 16, sharedExperts: 2, expertHidden: 3072,
      window: 128, topk: 512, candidatePool: 16384, cacheBytes: 0, context: 1048576,
      fullLayers: [3], reindexLayers: [], residualStreams: 4,
      metricResidual: 'AttnRes<small>selective cross-layer retrieval</small>',
      metricVision: 'MoonViT-V2<small>401M · patch 14 · 12 heads</small>',
      metricDraft: 'MTP<small>multi-token prediction head</small>',
      metricHead: 'Vocabulary head<small>160K entries</small>',
      vocab: 160000,
    },
    summary: 'Open 2.8T/104B: 69 KDA + 24 Gated MLA, Stable LatentMoE, AttnRes, MoonViT-V2.',
    sources: [
      { title: 'Hugging Face model card', url: 'https://huggingface.co/moonshotai/Kimi-K3', note: '2.8T / 104B, 93 layers, 69 KDA + 24 Gated MLA.' },
      { title: 'Technical report', url: 'https://arxiv.org/html/2607.24653v1', note: 'Kimi K3: Open Frontier Intelligence.' },
      { title: 'Official blog', url: 'https://www.kimi.com/blog/kimi-k3', note: 'AttnRes, Stable LatentMoE, MoonViT-V2.' },
    ],
    notes: [
      'Attention repeats 3×KDA + 1×Gated MLA; the last layer is MLA (69+24).',
      'MLA uses NoPE and compressed latent KV; 1M extrapolation leans on KDA decay/gating.',
    ],
    roles: { attn:'encoder_kda0', sparse:'encoder_mla', index:'latent_router', moe:'encoder_moe_mla', residual:'embedding', memory:'hidden_states', vision:'vision_encoder', projector:'vision_embedding', head:'target_head', draft:'mtp' },
    beats: {
      stack:'93 layers · 2.8T / 104B.',
      attn:'Kimi Delta Attention, 96 heads, fixed state.',
      sparse:'Gated MLA every 4th layer, NoPE, compressed latent KV.',
      moe:'16 of 896 routed + 2 shared (LatentMoE).',
      residual:'AttnRes selective cross-layer retrieval.',
      memory:'Latent KV for MLA; latent router at 3,584-d before expert dispatch.',
      vision:'MoonViT-V2, 401M.',
      output:'Vocabulary head + MTP.',
    },
  },
  {
    id: 'glm5',
    name: 'GLM-5',
    short: 'GLM-5',
    year: '2026',
    tagline: '78 layers · 8+1 / 256',
    accent: 0x2dd4bf,
    modern: true,
    source: 'build',
    spatial: glm5Spatial,
    facts: {
      layers: 78, encoder: 0, decoder: 78, hidden: 6144, heads: 64, headDim: 128,
      routedExperts: 256, activeExperts: 8, sharedExperts: 1, expertHidden: 2048,
      window: 2048, topk: 2048, candidatePool: 16384, cacheBytes: 512, context: 202752,
      fullLayers: [3], reindexLayers: [8], residualStreams: 1,
      metricResidual: 'Residual + RMSNorm<small>pre-norm around MLA / MoE</small>',
      metricDraft: 'MTP<small>multi-token prediction head</small>',
      metricHead: 'Vocabulary head<small>154,880 entries</small>',
      vocab: 154880,
    },
    summary: 'Official HF config: 744B / 40B, 78 layers. First 3 dense; then MLA + DSA MoE.',
    sources: [
      { title: 'Hugging Face config.json', url: 'https://huggingface.co/zai-org/GLM-5/blob/main/config.json', note: 'GlmMoeDsaForCausalLM: 78 layers, 256 routed experts, index_topk=2048.' },
      { title: 'Official blog', url: 'https://z.ai/blog/glm-5', note: '355B-A32B → 744B-A40B, introducing DSA.' },
      { title: 'Technical report', url: 'https://arxiv.org/html/2602.15763v2', note: 'GLM-5: from Vibe Coding to Agentic Engineering.' },
    ],
    notes: [
      'Use the official 744B/40B figures, not the 774B copy that appears in some notes.',
      'DSA selects at most 2,048 KV entries; q_lora_rank=2048, kv_lora_rank=512.',
    ],
    roles: { attn:'dense_attn', sparse:'encoder_dsa', index:'candidate_pool', moe:'encoder_moe_dsa', residual:'embedding', memory:'hidden_states', vision:null, projector:null, head:'target_head', draft:'mtp' },
    beats: {
      stack:'78 layers · 744B / 40B; first 3 dense.',
      attn:'MLA, 64 heads, KV rank 512.',
      sparse:'DSA top-k 2,048 over compressed KV.',
      moe:'8 of 256 routed + 1 shared.',
      residual:'Pre-norm residual around MLA / MoE.',
      memory:'Compressed latent KV (lora 512).',
      vision:'Text-only in this drawing.',
      output:'Vocabulary head + MTP.',
    },
  },
  {
    id: 'gemma4',
    name: 'Gemma 4 31B',
    short: 'Gemma 4',
    year: '2026',
    tagline: '60 layers · 5:1 SWA/Global',
    accent: 0x5b8def,
    modern: true,
    source: 'build',
    spatial: gemma4Spatial,
    facts: {
      layers: 60, encoder: 0, decoder: 60, hidden: 5376, heads: 32, headDim: 256,
      routedExperts: 0, activeExperts: 0, sharedExperts: 0, expertHidden: 21504,
      window: 1024, topk: 0, candidatePool: 0, cacheBytes: 0, context: 262144,
      fullLayers: [5, 11, 17, 23, 29, 35, 41, 47, 53, 59], reindexLayers: [], residualStreams: 1,
      metricResidual: 'RMSNorm residual<small>pre-norm around SWA / Global / FFN</small>',
      metricVision: 'ViT · 550M<small>27 layers · hidden 1,152 · patch 16 · 280 tokens</small>',
      metricDraft: 'MTP drafter<small>4 layers · dim 1,024 · 3 local + 1 global</small>',
      metricHead: 'Tied vocabulary head<small>262,144 entries</small>',
      metricFfn: 'dense GeLU<small>width 21,504 · no MoE</small>',
      metricHidden: 'Global KV<small>4 KV heads · unified K = V</small>',
      metricMemory: 'SWA 1,024<small>local window on sliding layers</small>',
      vocab: 262144,
    },
    summary: 'Gemma 4 31B dense: 60 layers, 10 × (5 SWA + 1 Global). Sliding window 1,024; global layers use 4 KV heads with K = V. Native ViT, no audio encoder.',
    sources: [
      { title: 'Official config.json', url: 'https://huggingface.co/google/gemma-4-31B-it/blob/main/config.json', note: 'Gemma4ForConditionalGeneration: 60 layers, layer_types 5:1 SWA/Global, sliding_window=1024, enable_moe_block=false.' },
      { title: 'Technical report', url: 'https://arxiv.org/html/2607.02770', note: 'Gemma 4: 31B dense, 550M ViT, p-RoPE on global layers, 4-layer MTP drafter.' },
      { title: 'Model card', url: 'https://huggingface.co/google/gemma-4-31B-it', note: 'Hybrid local/global attention; global layers unify Keys and Values; 256K context.' },
    ],
    notes: [
      'This drawing is the 31B dense checkpoint, not 26B-A4B MoE or the 12B unified encoder-free model.',
      'Global layers: 32 Q / 4 KV, head_dim 512, K = V. Local SWA: 32 Q / 16 KV, head_dim 256, window 1,024.',
      'The 4-layer MTP assistant is a separate drafter that cross-attends to the target KV; it is not an extra backbone layer.',
    ],
    roles: { attn:'encoder_swa', sparse:'encoder_global', index:'local_window', moe:'encoder_ffn_global', residual:'embedding', memory:'global_kv', vision:'vision_encoder', projector:'vision_embedding', head:'target_head', draft:'mtp' },
    beats: {
      stack:'60 dense layers · 31B; 10 × (5 SWA + 1 Global).',
      attn:'Local SWA, 32 Q / 16 KV, window 1,024.',
      sparse:'Global attention every 6th layer; 4 KV heads, K = V.',
      moe:'Dense GeLU FFN, width 21,504; no experts.',
      residual:'Pre-norm RMSNorm residual.',
      memory:'Global KV is 4-head and unified K = V; local SWA keeps its own 1,024-token window.',
      vision:'550M ViT, 27 layers, patch 16, default 280 tokens. No audio encoder on 31B.',
      output:'Tied vocabulary head + 4-layer MTP drafter.',
    },
  },
  {
    id: 'minimax-m25',
    name: 'MiniMax M2.5',
    short: 'MiniMax M2.5',
    year: '2026',
    tagline: '62 layers · 8 / 256',
    accent: 0xf97316,
    modern: true,
    source: 'build',
    spatial: minimaxM25Spatial,
    facts: {
      layers: 62, encoder: 0, decoder: 62, hidden: 3072, heads: 48, headDim: 128,
      routedExperts: 256, activeExperts: 8, sharedExperts: 0, expertHidden: 1536,
      window: 0, topk: 0, candidatePool: 0, cacheBytes: 0, context: 196608,
      fullLayers: [], reindexLayers: [], residualStreams: 1,
      metricResidual: 'RMSNorm residual<small>pre-norm around GQA / MoE</small>',
      metricDraft: 'MTP ×3<small>3 modules · 1 transformer layer each</small>',
      metricHead: 'Vocabulary head<small>200,064 entries</small>',
      vocab: 200064,
    },
    summary: 'MiniMax-M2.5 config: 229B / 10B, 62 layers. All-GQA attention, 8 of 256 routed experts, no shared expert, MTP ×3.',
    sources: [
      { title: 'Official config.json', url: 'https://huggingface.co/MiniMaxAI/MiniMax-M2.5/blob/main/config.json', note: 'MiniMaxM2ForCausalLM: 62 layers, attn_type_list all 1 (full GQA), 256 routed experts top-8, shared_intermediate_size=0.' },
      { title: 'Model card', url: 'https://huggingface.co/MiniMaxAI/MiniMax-M2.5', note: '229B total parameters; 196,608 context; 3 MTP modules.' },
    ],
    notes: [
      'Every layer is the same GQA + MoE pair. The drawing unrolls two layers; the outer cage is ×31, not shared weights.',
      'No shared expert (shared_intermediate_size=0). Routing uses sigmoid scores with a learned bias. Partial RoPE (rotary_dim=64 of 128) and QK-Norm sit inside GQA, not as side modules.',
    ],
    roles: { attn:'encoder_gqa0', sparse:'encoder_gqa', index:null, moe:'encoder_moe', residual:'embedding', memory:null, vision:null, projector:null, head:'target_head', draft:'mtp' },
    beats: {
      stack:'62 identical layers · 229B / 10B.',
      attn:'GQA on every layer, 48 Q / 8 KV, head_dim 128.',
      sparse:'No sliding window or retrieval indexer; full GQA throughout.',
      moe:'8 of 256 routed experts; no shared expert.',
      residual:'Pre-norm RMSNorm residual.',
      memory:'No extra parameter memory; KV is ordinary GQA cache.',
      vision:'Text-only in this drawing.',
      output:'Untied vocabulary head + 3 MTP modules.',
    },
  },
  {
    id: 'step35',
    name: 'Step 3.5 Flash',
    short: 'Step 3.5',
    year: '2026',
    tagline: '45 layers · 8+1 / 288',
    accent: 0x38bdf8,
    modern: true,
    source: 'build',
    spatial: step35Spatial,
    facts: {
      layers: 45, encoder: 0, decoder: 45, hidden: 4096, heads: 64, headDim: 128,
      routedExperts: 288, activeExperts: 8, sharedExperts: 1, expertHidden: 1280,
      window: 512, topk: 0, candidatePool: 0, cacheBytes: 0, context: 262144,
      fullLayers: [0, 4], reindexLayers: [], residualStreams: 1,
      metricResidual: 'RMSNorm residual<small>pre-norm around Full / SWA / FFN</small>',
      metricDraft: 'MTP-3<small>3 next-n layers · 4 tokens per pass</small>',
      metricHead: 'Vocabulary head<small>128,896 entries</small>',
      metricFfn: 'dense SwiGLU<small>layers 0–2 · no expert routing</small>',
      metricMemory: 'SWA 512<small>local window on sliding layers</small>',
      vocab: 128896,
    },
    summary: 'Step-3.5-Flash config: 196B / 11B, 45 layers. Leading Full, then 11 × (3 SWA + 1 Full). First 3 FFN dense; 288 routed + 1 shared.',
    sources: [
      { title: 'Official config.json', url: 'https://huggingface.co/stepfun-ai/Step-3.5-Flash/blob/main/config.json', note: 'Step3p5ForCausalLM: 45 layers, moe_layers_enum 3–44, SWA window 512, 288 routed top-8, share_expert_dim=1280.' },
      { title: 'Technical report', url: 'https://arxiv.org/html/2602.10604', note: 'Step 3.5 Flash: Open Frontier-Level Intelligence with 11B Active Parameters.' },
      { title: 'Model card', url: 'https://huggingface.co/stepfun-ai/Step-3.5-Flash', note: '196B / 11B, 256K context, MTP-3, text-only.' },
    ],
    notes: [
      'layer_types has 48 entries; the last 3 are MTP, not backbone. Backbone is 1 Full + 11 × (3 SWA + 1 Full).',
      'Full layers: 64 Q heads / 8 groups. SWA layers: 96 Q heads / 8 groups, window 512, head-wise attention gate.',
      'FFN layers 0–2 are dense; MoE starts at layer 3, so the first hybrid cell still mixes two dense SWA FFNs with MoE.',
    ],
    roles: { attn:'encoder_full0', sparse:'encoder_swa', index:'local_window', moe:'encoder_moe_swa', residual:'embedding', memory:'local_window', vision:null, projector:null, head:'target_head', draft:'mtp' },
    beats: {
      stack:'45 layers · 196B / 11B; lead Full then 11 × (3 SWA + 1 Full).',
      attn:'Full GQA, 64 heads / 8 groups.',
      sparse:'SWA 96 heads, window 512, three SWA per Full.',
      moe:'8 of 288 routed + 1 shared; first 3 FFN dense.',
      residual:'Pre-norm RMSNorm residual.',
      memory:'Local SWA cache of 512 tokens; no retrieval indexer.',
      vision:'Text-only in this drawing.',
      output:'Untied vocabulary head + MTP-3.',
    },
  },
];

export function getModel(id) {
  return MODELS.find((m) => m.id === id) || MODELS[0];
}

export const DEFAULTS = ['qwen38', 'deepseek-v4'];
